sudo: required

services:
  - docker

before_script: env && pip3 install -r contrib/mmts/tests2/requirements.txt

# script: cd contrib/mmts/tests2 && python3 test_regression.py
script: cd contrib/mmts/tests2 && python3 test_recovery.py

notifications:
  email:
    - s.kelvich@postgrespro.ru


# language: perl
# os:
#   - linux
#   #- osx
# compiler:
#   - gcc
#   - clang
# install: cpanm IPC::Run DBD::Pg Proc::ProcessTable
# before_script: ./configure --enable-cassert --enable-tap-tests && make -j4
# env:
#   #- TESTDIR=.
#   #- TESTDIR=src/test/recovery
#   - TESTDIR=contrib/raftable
#   - TESTDIR=contrib/mmts
# script: cd $TESTDIR && make check
# notifications:
#   email:
#     - s.kelvich@postgrespro.ru
#     - c.pan@postgrespro.ru
#     - k.knizhnik@postgrespro.ru

